import { Poppins } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";

const inter = Poppins({ subsets: ["latin"], weight:["400", "500","600","700","800","900"] });

export const metadata = {
  title: "1 Link | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <link rel="icon" href="/logo.png" />
        <Header/>
        <div className=" pt-14 ">

        {children}
        </div>
        
        </body>
    </html>
  );
}
