 
import { Poppins } from "next/font/google";
import "../globals.css"; 
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import UserSideBar from "@/components/UserSideBar";
import { authOptions } from "../api/auth/[...nextauth]/route"; 
import { Toaster } from "react-hot-toast"
import ConnectDb from "@/lib/connect";
import { PageModel } from "@/models/Page";
const inter = Poppins({ subsets: ["latin"], weight:["400", "500","600","700","800","900"] });

export const metadata = {
  title: "Account",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session=await getServerSession(authOptions)
  if(!session){
    redirect('/')
  } 
  ConnectDb()
  const page = await PageModel.findOne({ owner: session?.user?.email }).lean();;
 
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster
          position="top-right"
          reverseOrder={true}
        /> 
        {children} 
        
        </body>
    </html>
  );
 
}
